### ISSUE TITLE
Running Backend and Frontend in same time 

### ISSUE THREAD

**Issue by koptan** [instamed/healthcare-payments-blockchain#1]
Hi , 

How to run the backend and frontend server in same time to do some development activity ?

**Comment by instameddevelopment** [comment]
Did you following the tutorial on 

https://developers.instamed.com/healthcare-payments-blockchain/install-blockchain-on-linux/

It walks you through setting up a dev box and getting the front end and backend running at the same time.

**Comment by instameddevelopment** [comment]
Did you following the tutorial on 

https://developers.instamed.com/healthcare-payments-blockchain/install-blockchain-on-linux/

It walks you through setting up a dev box and getting the front end and backend running at the same time.

**Comment by koptan** [comment]
@instameddevelopment  thanks for your reply ,,, 

But this tutorial will not run the frontend server in dev mode with hot reload feature .

As workaround from my side i am running the frontend server in different port and API server on different port .

If there is a better way please let me know .

thank you .

**Comment by instameddevelopment** [comment]
@koptan Running on two different ports is the best solution if you are wanting to use Vue's hot reload. Thanks for your question!
