### ISSUE TITLE
Installer.sh - missing databased

### ISSUE THREAD

**Issue by gnom1gnom** [instamed/healthcare-payments-blockchain#3]
OS: Ubuntu 18.04.3 LTS
Node: v8.11.4
npm: 5.6.0
hurl: 1.1.1

The _installer.sh_ script successfully created view in the _ch1_financial_ database, but failed for the rest, because these databases are missing:
- ch1_financial$$pabc_healthcare-instamed-xyz_provider
- ch1_financial$$pabc_healthcare-instamed
- ch1_financial$$pabc_healthcare-xyz_provider
- ch1_financial$$pinstamed-xyz_provider

When are these databases created and why are they missing in my setup?

**Comment by instameddevelopment** [comment]
These happened because no data were save in the private collections before re-installing the views. The readme is updated with more details steps in the installation section to avoid this issue.

**Comment by instameddevelopment** [comment]
Solved.
