### ISSUE TITLE
Terminal Hung after mockData

### ISSUE THREAD

**Issue by lawrenceong001** [instamed/healthcare-payments-blockchain#6]
There seems to be an issue when I try to run the guide on: https://developers.instamed.com/healthcare-payments-blockchain/install-blockchain-on-linux/ (Very well written though, thanks). after I followed everything to Step 10, I am stuck. the last line is 

`[hurley] - Result: {"type":"Buffer","data":[]}`

running step 12 -14 in a separate terminal, i'm also stuck at "Creating Claim", which ends with network error

**Comment by instameddevelopment** [comment]
Fixed issue by upgrading hurley version: 1.0.0 ~ 1.1.2.

**Comment by instameddevelopment** [comment]
Solved.
